authorization_handler:
  genders:
    - "Man"
    - "Woman"
    - "Other"
  ages:
    - "0-10"
    - "11-15"
    - "16-20"
    - "21-30"
    - "31-40"
    - "41-50"
    - "51-60"
    - "61-70"
    - "71-80"
    - "81-85"
    - "86-90"
    - "91-95"
    - "96-100"
    - "101-"
  zones:
    - "Don’t want to say"
    - "Bosatt i kranskommun till Göteborg"
    - "Bosatt i annan kommun i Sverige"
    - "Bosatt utanför Sverige"
    - "Nord-ost: Bergsjön"
    - "Nord-ost: Gamlestaden-Utby"
    - "Nord-ost: Kortedala"
    - "Nord-ost: Östra Angered"
    - "Nord-ost: Södra Angered"
    - "Nord-ost: Centrala Angered"
    - "Nord-ost: Norra Angered"
    - "Centrum: Kålltorp-Torpa-Björkekärr"
    - "Centrum: Kallebäck-Skår-Kärralund"
    - "Centrum: Krokslätt-Johanneberg"
    - "Centrum: Guldheden-Landala"
    - "Centrum: Olivedal-Haga-Annedal-Änggården"
    - "Centrum: Kungsladugård-Sanna"
    - "Centrum: Majorna-Stigberget-Masthugget"
    - "Centrum: Norra centrum"
    - "Centrum: Lunden-Härlanda-Överås"
    - "Centrum: Olskroken-Redbergslid-Bagaregården"
    - "Sydväst: Stora Högsbo"
    - "Sydväst: Askim-Hovås"
    - "Sydväst: Billdal"
    - "Sydväst: Södra Skärgården"
    - "Sydväst: Bratthammar-Näset-Önnered"
    - "Sydväst: Centrala Tynnered"
    - "Sydväст: Frölunda Torg-Tofta"
    - "Sydväst: Älvsborg"
    - "Hisingen: Kärra-Rödbo"
    - "Hisingen: Backa"
    - "Hisingen: Kvillebäcken"
    - "Hisingen: Kyrkbyn-Rambergsstaden"
    - "Hisingen: Norra Älvstranden"
    - "Hisingen: Södra Torslanda"
    - "Hisingen: Björlanda"
    - "Hisingen: Tuve-Säve"
    - "Hisingen: Kärrdalen-Slättadamm"
    - "Hisingen: Östra Biskopsgården"
    - "Hisingen: Västra Biskopsgården"
