---

base_locale: en
locales: [en, fr]

ignore_unused:
  - "decidim.components.socio_demographic_authorization_handler.name"
  - "decidim.authorization_handlers.socio_demographic_authorization_handler.fields.participation_process"
  - "decidim.authorization_handlers.socio_demographic_authorization_handler.name"
  - "decidim.authorization_handlers.socio_demographic_authorization_handler.explanation"
  - "decidim.verifications.genders.man"
  - "decidim.verifications.genders.woman"
  - "decidim.verifications.genders.other"

ignore_missing:
  - decidim.participatory_processes.scopes.global
