name: "[CI] Lint"

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 3.1.6
  NODE_VERSION: 18.17.1

jobs:
  lint-report:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: npm ci
        name: Install JS deps

      - run: bundle exec rubocop -P
        name: Lint Ruby files
